#!/bin/bash
# ardyh_hub daemon
# chkconfig: 345 20 80
# description: ardyh_hub daemon
# processname: ardyh_hub

DAEMON_PATH="/home/pi/projects/lilybot/hub"

DAEMON=start_hub.sh
DAEMONOPTS=""

NAME=ardyh_hubd
DESC="This starts the Ardyh hub"
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME
PORT=9010

case "$1" in
start)
    printf "%-50s" "Starting $NAME on port $PORT..."
    cd $DAEMON_PATH
    PID=`./$DAEMON $DAEMONOPTS > /dev/null  2>&1 & echo $!`

    if [ -z $PID ]; then
        printf "%s\n" "Fail"
    else
        echo $PID > $PIDFILE
        printf "%s\n" "Ok"
    fi

    # printf "Starting camera server on port 8080"
    # mkdir /tmp/stream
    # raspistill --nopreview -w 640 -h 480 -q 5 -o /tmp/stream/pic.jpg -tl 100 -t 9999999 -th 0:0:0 &
    # LD_LIBRARY_PATH=/usr/local/lib mjpg_streamer -i "input_file.so -f /tmp/stream -n pic.jpg" -o "output_http.so -w /home/pi/Projects/lilybot/jjbot/www" &


;;
status)
        printf "%-50s" "Checking $NAME..."
        if [ -f $PIDFILE ]; then
            PID=`cat $PIDFILE`
            if [ -z "`ps axf | grep ${PID} | grep -v grep`" ]; then
                printf "%s\n" "Process dead but pidfile exists"
            else
                echo "Running"
            fi
        else
            printf "%s\n" "Service not running"
        fi
;;
stop)
        printf "%-50s" "Stopping $NAME"
            PID=`cat $PIDFILE`
            cd $DAEMON_PATH
        if [ -f $PIDFILE ]; then
            kill -HUP $PID
            printf "%s\n" "Ok"
            rm -f $PIDFILE
            echo "Releasing port $PORT"
            fuser -k $PORT/tcp
        else
            printf "%s\n" "pidfile not found"
        fi
;;

restart)
    $0 stop
    $0 start
;;

*)
        echo "Usage: $0 {status|start|stop|restart}"
        exit 1
esac
